parameters:
  your_component:
    some_parameter: true

  kapitan:

    compile:
      - output_path: .
        input_type: jinja2
        input_paths:
          - templates/docs

      - output_path: manifests
        input_type: jinja2
        output_type: html
        input_paths:
          - templates/nginx.conf

      - output_path: manifests/html
        input_type: jinja2
        input_paths:
          - templates/*.html

      - output_path: .
        input_type: jinja2
        input_paths:
          - templates/scripts/
